import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {collectMedia, digest, inside} from './media-library.mjs';

export async function prepareMedia(project = process.cwd(), initialize = false) {
const root = path.join(project, '素材库');
const slots = JSON.parse(await fs.readFile(path.join(root,'素材位配置.json'),'utf8'));
for (const slot of Object.values(slots)) await fs.mkdir(path.dirname(inside(root,slot.file)),{recursive:true});
// One-time migration only. Normal builds never silently restore a deleted/replaced source.
if (initialize) {
  const seeds = {
    brandLogo:'brand/lumen-auralis-official-logo.png', loaderArt:'brand/brand-loader-line-art-regenerated-circle-v4.png',
    loaderStar:'brand/brand-loader-star-dot-transparent-v3.png', jingxinConcept:'bjd/lotus-goddess-concept.png',
    jingxinPortrait:'bjd/lotus-goddess-transparent.png', lotusRelief:'brand/lotus-relief-sides.png',
  };
  for (const [id, old] of Object.entries(seeds)) {
    const source = inside(path.join(project,'public/images'),old);
    const target = inside(root,slots[id].file+'.png');
    try { await fs.copyFile(source,target,fs.constants.COPYFILE_EXCL); }
    catch (error) { if (error.code !== 'EEXIST') throw error; continue; }
    if (digest(await fs.readFile(source)) !== digest(await fs.readFile(target))) throw Error(`迁移校验失败：${id}`);
  }
}
const {entries,files} = await collectMedia(project);
const browser = Object.fromEntries(Object.entries(entries).map(([id,entry])=>[id,{src:entry.src,own:entry.own,alt:entry.alt}]));
const generated = '// Generated by npm run media:prepare. Edit 素材库, not this file.\n'+
  'export type MediaId = '+Object.keys(entries).map(id=>JSON.stringify(id)).join(' | ')+';\n'+
  'export const siteMedia: Record<MediaId, {src: string | null; own: boolean; alt: string}> = '+JSON.stringify(browser,null,2)+';\n';
await fs.mkdir(path.join(project,'src/generated'),{recursive:true});
await fs.writeFile(path.join(project,'src/generated/site-media.ts'),generated);
const rows = ['# 网站素材位清单','','此表自动更新；只替换“素材库”中的图片，不修改生成文件。尺寸均为宽 × 高。','','| 素材位 / 用途 | 替换文件（相对素材库） | 建议尺寸 | 当前状态 | 当前尺寸 |','| --- | --- | --- | --- | --- |'];
for (const [id,entry] of Object.entries(entries)) {
  const slot=entry.slot;
  rows.push(`| ${slot.usage} | ${slot.file}.{${slot.formats.join(',')}} | ${slot.size.join(' × ')} | ${entry.own?'已接入':entry.src?`复用 ${entries[slot.fallback].slot.file}`:'待补图，保留占位'} | ${entry.info?`${entry.info.width} × ${entry.info.height}`:'—'} |`);
}
await fs.writeFile(path.join(root,'素材位清单.md'),rows.join('\n')+'\n');
const escape = value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const localUrl = file=>file.split('/').map(encodeURIComponent).join('/');
const cards=Object.values(entries).map(entry=>{
  const imageEntry=entry.own?entry:entry.slot.fallback?entries[entry.slot.fallback]:null;
  const preview=imageEntry?.file?`<img loading="lazy" src="${localUrl(imageEntry.file)}" alt="${escape(entry.alt)}">`:'<div class="empty">待补图</div>';
  return `<article>${preview}<h2>${escape(entry.slot.usage)}</h2><p>${escape(entry.slot.file)}<br>允许格式：${escape(entry.slot.formats.join(' / '))}</p><p>建议：${entry.slot.size.join(' × ')}<br>${entry.own?'已接入':entry.src?'复用角色默认图':'保留占位，尚未发布照片'}</p><small>${escape(entry.slot.note||'替换后重新构建。不要直接修改生成文件。')}</small></article>`;
}).join('');
await fs.writeFile(path.join(root,'素材位预览.html'),`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>网站素材库 · 替换位置</title><style>body{font:16px/1.6 system-ui;background:#e0ede6;color:#123f36;margin:32px}header{max-width:900px}main{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:20px}article{background:#f0f6f2;padding:20px}h2{font-size:18px}img,.empty{width:100%;height:200px;object-fit:contain;background:#c3ded3}.empty{display:grid;place-items:center}p,small{overflow-wrap:anywhere}small{font-size:14px}</style><header><h1>网站素材位 · 25 个</h1><p>这些目录中的图片真正连接网页。按相同文件名替换，然后双击“更新图片预览.cmd”。此索引与中文历史备份都不会发布到网站。官方摄影与返图只放已获准公开的图片。</p><p>换 JPG / PNG / WebP 时只保留同名的一种格式；透明素材保持 PNG。网页上线后还需重新部署。</p></header><main>${cards}</main></html>`);
return {slots:Object.keys(entries).length, images:files.length};
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const result=await prepareMedia(process.cwd(),process.argv.includes('--init'));
  console.log(`素材位 ${result.slots} 个；独立在用图片 ${result.images} 张；原图未覆盖。`);
}
